version: "3.9"
services:
  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "33065:3306"
